<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Question;

class PythonOperatorsExpressionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::transaction(function () {

            $questions = [

                    //Topic id 15
                [
                    'question_text' => 'Which operator is used for addition in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'arithmetic'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10', 'all'],
                    'options' => [
                        ['option_text' => '+', 'is_correct' => true],
                        ['option_text' => '-', 'is_correct' => false],
                        ['option_text' => '*', 'is_correct' => false],
                        ['option_text' => '/', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which operator is used for subtraction in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'arithmetic'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '+', 'is_correct' => false],
                        ['option_text' => '-', 'is_correct' => true],
                        ['option_text' => '*', 'is_correct' => false],
                        ['option_text' => '%', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which operator is used for multiplication in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'arithmetic'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '*', 'is_correct' => true],
                        ['option_text' => 'x', 'is_correct' => false],
                        ['option_text' => '/', 'is_correct' => false],
                        ['option_text' => '+', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which operator is used for division in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'division'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '/', 'is_correct' => true],
                        ['option_text' => '//', 'is_correct' => false],
                        ['option_text' => '%', 'is_correct' => false],
                        ['option_text' => '*', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What does the % operator do in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'modulus'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Returns remainder', 'is_correct' => true],
                        ['option_text' => 'Performs division', 'is_correct' => false],
                        ['option_text' => 'Performs multiplication', 'is_correct' => false],
                        ['option_text' => 'Rounds result', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which operator performs floor division in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'floor-division'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '//', 'is_correct' => true],
                        ['option_text' => '/', 'is_correct' => false],
                        ['option_text' => '%', 'is_correct' => false],
                        ['option_text' => '**', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which operator is used for exponentiation in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'power'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '**', 'is_correct' => true],
                        ['option_text' => '^', 'is_correct' => false],
                        ['option_text' => '*', 'is_correct' => false],
                        ['option_text' => '//', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of: 10 + 5 * 2?',
                    'question_code' => '10 + 5 * 2',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '20', 'is_correct' => true],
                        ['option_text' => '30', 'is_correct' => false],
                        ['option_text' => '15', 'is_correct' => false],
                        ['option_text' => '25', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of: 20 // 3?',
                    'question_code' => '20 // 3',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'floor-division'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '6', 'is_correct' => true],
                        ['option_text' => '6.66', 'is_correct' => false],
                        ['option_text' => '7', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of: 7 % 3?',
                    'question_code' => '7 % 3',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'modulus'],
                    'applicable_to' => ['class_8', 'class_9'],
                    'options' => [
                        ['option_text' => '1', 'is_correct' => true],
                        ['option_text' => '2', 'is_correct' => false],
                        ['option_text' => '3', 'is_correct' => false],
                        ['option_text' => '0', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which operator has the highest precedence?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '**', 'is_correct' => true],
                        ['option_text' => '*', 'is_correct' => false],
                        ['option_text' => '+', 'is_correct' => false],
                        ['option_text' => '-', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of: 2 ** 3 ** 2?',
                    'question_code' => '2 ** 3 ** 2',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'power'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '512', 'is_correct' => true],
                        ['option_text' => '64', 'is_correct' => false],
                        ['option_text' => '36', 'is_correct' => false],
                        ['option_text' => '16', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which arithmetic operator can be used with strings?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'string'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '+', 'is_correct' => true],
                        ['option_text' => '/', 'is_correct' => false],
                        ['option_text' => '%', 'is_correct' => false],
                        ['option_text' => '//', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of: "Hi" * 3?',
                    'question_code' => '"Hi" * 3',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'string'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'HiHiHi', 'is_correct' => true],
                        ['option_text' => 'Hi*3', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'Hi Hi Hi', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which arithmetic operator cannot be used with strings?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'string'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '-', 'is_correct' => true],
                        ['option_text' => '+', 'is_correct' => false],
                        ['option_text' => '*', 'is_correct' => false],
                        ['option_text' => '**', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'print(8 + 4 / 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '10.0', 'is_correct' => true],
                        ['option_text' => '6', 'is_correct' => false],
                        ['option_text' => '12', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'print((8 + 4) / 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '6.0', 'is_correct' => true],
                        ['option_text' => '10', 'is_correct' => false],
                        ['option_text' => '12', 'is_correct' => false],
                        ['option_text' => '4', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'print(15 % 4 + 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'modulus'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '5', 'is_correct' => true],
                        ['option_text' => '3', 'is_correct' => false],
                        ['option_text' => '6', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'print(2 * 3 ** 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'power'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '18', 'is_correct' => true],
                        ['option_text' => '36', 'is_correct' => false],
                        ['option_text' => '12', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'print(9 // 2 + 1)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 15,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'floor-division'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '5', 'is_correct' => true],
                        ['option_text' => '4.5', 'is_correct' => false],
                        ['option_text' => '6', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                //Topic id 16

                [
                    'question_text' => 'Which operator is used for simple assignment in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'assignment', 'operators'],
                    'applicable_to' => ['class_8', 'class_9'],
                    'options' => [
                        ['option_text' => '=', 'is_correct' => true],
                        ['option_text' => '==', 'is_correct' => false],
                        ['option_text' => '+=', 'is_correct' => false],
                        ['option_text' => '=>', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which of the following is a compound assignment operator?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'assignment', 'compound'],
                    'applicable_to' => ['class_8', 'class_9'],
                    'options' => [
                        ['option_text' => '+=', 'is_correct' => true],
                        ['option_text' => '==', 'is_correct' => false],
                        ['option_text' => '=', 'is_correct' => false],
                        ['option_text' => '!=', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 5\nx += 3\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'assignment', 'compound'],
                    'applicable_to' => ['class_8', 'class_9'],
                    'options' => [
                        ['option_text' => '8', 'is_correct' => true],
                        ['option_text' => '5', 'is_correct' => false],
                        ['option_text' => '3', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 10\nx -= 4\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'assignment', 'compound'],
                    'applicable_to' => ['class_8', 'class_9'],
                    'options' => [
                        ['option_text' => '6', 'is_correct' => true],
                        ['option_text' => '14', 'is_correct' => false],
                        ['option_text' => '10', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 4\nx *= 2\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'assignment', 'compound'],
                    'applicable_to' => ['class_8', 'class_9'],
                    'options' => [
                        ['option_text' => '8', 'is_correct' => true],
                        ['option_text' => '6', 'is_correct' => false],
                        ['option_text' => '4', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 10\nx /= 4\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'division'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '2.5', 'is_correct' => true],
                        ['option_text' => '2', 'is_correct' => false],
                        ['option_text' => '3', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 10\nx //= 3\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'floor-division'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '3', 'is_correct' => true],
                        ['option_text' => '3.33', 'is_correct' => false],
                        ['option_text' => '4', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 5\nx **= 2\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'power'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '25', 'is_correct' => true],
                        ['option_text' => '10', 'is_correct' => false],
                        ['option_text' => '7', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 7\nx %= 3\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'modulus'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '1', 'is_correct' => true],
                        ['option_text' => '2', 'is_correct' => false],
                        ['option_text' => '3', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which statement is equivalent to: x += 5 ?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16, 
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'compound'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'x = x + 5', 'is_correct' => true],
                        ['option_text' => 'x == x + 5', 'is_correct' => false],
                        ['option_text' => 'x =+ 5', 'is_correct' => false],
                        ['option_text' => 'x = 5 + x only', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 5\ny = x\nx += 2\nprint(y)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'reference'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '5', 'is_correct' => true],
                        ['option_text' => '7', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 10\nx += x * 2\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'precedence'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '30', 'is_correct' => true],
                        ['option_text' => '40', 'is_correct' => false],
                        ['option_text' => '20', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 8\nx //= 3 + 1\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'floor-division'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '2', 'is_correct' => true],
                        ['option_text' => '1', 'is_correct' => false],
                        ['option_text' => '3', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 2\nx **= 3 ** 2\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'power'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '512', 'is_correct' => true],
                        ['option_text' => '64', 'is_correct' => false],
                        ['option_text' => '16', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 5\nx =+ 3\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'trap'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '3', 'is_correct' => true],
                        ['option_text' => '8', 'is_correct' => false],
                        ['option_text' => '5', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 4\ny = 2\nx += y += 3\nprint(x, y)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'compound'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '9 5', 'is_correct' => true],
                        ['option_text' => '7 5', 'is_correct' => false],
                        ['option_text' => '4 5', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 10\nx -= x // 3\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'floor'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '7', 'is_correct' => true],
                        ['option_text' => '6', 'is_correct' => false],
                        ['option_text' => '3', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 3\nx *= x + 2\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'precedence'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '15', 'is_correct' => true],
                        ['option_text' => '11', 'is_correct' => false],
                        ['option_text' => '9', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 5\nx %= 3 * 2\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'modulus'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '5', 'is_correct' => true],
                        ['option_text' => '1', 'is_correct' => false],
                        ['option_text' => '2', 'is_correct' => false],
                        ['option_text' => '0', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'x = 1\nx += 1 == 1\nprint(x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 16,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'assignment', 'boolean'],
                    'applicable_to' => ['class_10'],
                    'options' => [
                        ['option_text' => '2', 'is_correct' => true],
                        ['option_text' => '1', 'is_correct' => false],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],
                //Topic id 17
                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'print(5 == 5.0)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'comparison', 'equality'],
                    'applicable_to' => ['class_10', 'class_11', 'college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(5 is 5)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'identity'],
                    'applicable_to' => ['class_11', 'college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Syntax Error', 'is_correct' => false],
                        ['option_text' => 'Depends on Python version', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'a = 300\nb = 300\nprint(a is b)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'is-operator'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(10 != 10)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'comparison', 'not-equal'],
                    'applicable_to' => ['class_9', 'class_10', 'college'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(5 < 10 < 15)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'comparison', 'chaining'],
                    'applicable_to' => ['class_10', 'class_11', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(5 < 10 > 20)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'chaining'],
                    'applicable_to' => ['class_11', 'college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print("10" > "2")',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'string'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(True > False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'comparison', 'boolean'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which comparison returns True?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'logic'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => '[] == False', 'is_correct' => false],
                        ['option_text' => '[] == 0', 'is_correct' => false],
                        ['option_text' => '[] == []', 'is_correct' => true],
                        ['option_text' => '[] is []', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'x = None\nprint(x == False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'none'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(1 == True)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'comparison', 'boolean'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(0 is False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'identity'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'Depends on version', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'a = [1,2]\nb = [1,2]\nprint(a == b)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'comparison', 'list'],
                    'applicable_to' => ['class_11', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'a = [1,2]\nb = [1,2]\nprint(a is b)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'identity'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print("apple" < "banana")',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'comparison', 'string'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which of the following comparisons is TRUE?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'tricky'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'None == 0', 'is_correct' => false],
                        ['option_text' => 'None == False', 'is_correct' => false],
                        ['option_text' => 'None is None', 'is_correct' => true],
                        ['option_text' => 'None > 0', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(3 >= 3 >= 3)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'comparison', 'chaining'],
                    'applicable_to' => ['class_11', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(2 < 3 == 3)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'chaining'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'x = float("nan")\nprint(x == x)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'nan'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which comparison will raise an error in Python 3?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 17,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'comparison', 'error'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => '5 < "5"', 'is_correct' => true],
                        ['option_text' => '5 == "5"', 'is_correct' => false],
                        ['option_text' => '5 != "5"', 'is_correct' => false],
                        ['option_text' => '5 is 5', 'is_correct' => false],
                    ],
                ],
                //Topic id 18
                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'print(True and False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'and'],
                    'applicable_to' => ['class_9', 'class_10', 'college'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(True or False and False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'precedence'],
                    'applicable_to' => ['class_11', 'college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(not True == False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'not'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(5 and 0)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'truthy'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => '0', 'is_correct' => true],
                        ['option_text' => '5', 'is_correct' => false],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(0 or 7)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'or'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => '7', 'is_correct' => true],
                        ['option_text' => '0', 'is_correct' => false],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print("" or "Python")',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'string'],
                    'applicable_to' => ['class_11', 'college'],
                    'options' => [
                        ['option_text' => 'Python', 'is_correct' => true],
                        ['option_text' => '""', 'is_correct' => false],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(not 5 > 3 and 2 < 4)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'precedence'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(True and [] or [1])',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'list'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => '[1]', 'is_correct' => true],
                        ['option_text' => '[]', 'is_correct' => false],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which expression evaluates to False?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'tricky'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True and 1', 'is_correct' => false],
                        ['option_text' => '0 or False', 'is_correct' => true],
                        ['option_text' => 'not 0', 'is_correct' => false],
                        ['option_text' => 'True or False', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(not not True)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'double-not'],
                    'applicable_to' => ['class_9', 'class_10', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(10 and 20)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'and', 'truthy'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => '20', 'is_correct' => true],
                        ['option_text' => '10', 'is_correct' => false],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(0 and 10)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'and'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => '0', 'is_correct' => true],
                        ['option_text' => '10', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(0 or None or 5)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'or', 'short-circuit'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => '5', 'is_correct' => true],
                        ['option_text' => '0', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(False or [] or {})',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'falsy'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => '{}', 'is_correct' => true],
                        ['option_text' => '[]', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(not False and False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'precedence'],
                    'applicable_to' => ['class_11', 'college'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(not (False and True))',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'not'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'x = 5\nprint(x > 3 and x < 10 and x == 5)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'logical', 'comparison'],
                    'applicable_to' => ['class_11', 'college'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(True and None or False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'none'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which expression evaluates to True?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'tricky'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => '0 and True', 'is_correct' => false],
                        ['option_text' => '[] or False', 'is_correct' => false],
                        ['option_text' => 'not []', 'is_correct' => true],
                        ['option_text' => 'None and True', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(bool("False") and False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 18,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'logical', 'bool'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => '"False"', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                // Topic id 19
                [
                    'question_text' => 'Predict the output using operator precedence rules',
                    'question_code' => 'print(10 + 5 * 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_9', 'class_10', 'college'],
                    'options' => [
                        ['option_text' => '20', 'is_correct' => true],
                        ['option_text' => '30', 'is_correct' => false],
                        ['option_text' => '25', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Determine the output based on operator precedence',
                    'question_code' => 'print((10 + 5) * 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_9', 'class_10', 'college'],
                    'options' => [
                        ['option_text' => '30', 'is_correct' => true],
                        ['option_text' => '20', 'is_correct' => false],
                        ['option_text' => '25', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Evaluate the result considering operator precedence',
                    'question_code' => 'print(100 / 10 * 5)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => '50.0', 'is_correct' => true],
                        ['option_text' => '2.0', 'is_correct' => false],
                        ['option_text' => '20.0', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Predict the output using operator precedence',
                    'question_code' => 'print(8 - 3 ** 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'operators', 'precedence', 'power'],
                    'applicable_to' => ['class_11', 'college', 'advanced'],
                    'options' => [
                        ['option_text' => '-1', 'is_correct' => true],
                        ['option_text' => '25', 'is_correct' => false],
                        ['option_text' => '1', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Determine the output considering operator precedence',
                    'question_code' => 'print(2 ** 3 ** 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'operators', 'precedence', 'associativity'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => '512', 'is_correct' => true],
                        ['option_text' => '64', 'is_correct' => false],
                        ['option_text' => '256', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Predict the output based on operator precedence',
                    'question_code' => 'print(5 + 2 > 6 == True)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'operators', 'precedence', 'comparison'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Evaluate the output considering precedence of logical operators',
                    'question_code' => 'print(True or False and False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'operators', 'precedence', 'logical'],
                    'applicable_to' => ['class_11', 'college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Predict the output using operator precedence',
                    'question_code' => 'print(not False and False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence', 'not'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Determine the output based on operator precedence',
                    'question_code' => 'print(10 == 10 or 5 > 3 and 2 < 1)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 3,
                    'question_tags' => ['python', 'operators', 'precedence', 'logical'],
                    'applicable_to' => ['college', 'advanced'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => true],
                        ['option_text' => 'False', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Predict the output using operator precedence rules',
                    'question_code' => 'print(4 * 3 ** 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence', 'power'],
                    'applicable_to' => ['class_10', 'college'],
                    'options' => [
                        ['option_text' => '36', 'is_correct' => true],
                        ['option_text' => '144', 'is_correct' => false],
                        ['option_text' => '48', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which operator has the highest precedence in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_9', 'class_10', 'all'],
                    'options' => [
                        ['option_text' => 'Addition (+)', 'is_correct' => false],
                        ['option_text' => 'Multiplication (*)', 'is_correct' => false],
                        ['option_text' => 'Exponentiation (**)', 'is_correct' => true],
                        ['option_text' => 'Subtraction (-)', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following code?',
                    'question_code' => 'print(2 + 3 * 4)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'precedence', 'output'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '20', 'is_correct' => false],
                        ['option_text' => '14', 'is_correct' => true],
                        ['option_text' => '24', 'is_correct' => false],
                        ['option_text' => '9', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following Python code?',
                    'question_code' => 'print(10 - 4 ** 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence', 'power'],
                    'applicable_to' => ['class_10', 'all'],
                    'options' => [
                        ['option_text' => '-6', 'is_correct' => true],
                        ['option_text' => '36', 'is_correct' => false],
                        ['option_text' => '12', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which expression is evaluated first in the expression 5 + 6 * 2?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '5 + 6', 'is_correct' => false],
                        ['option_text' => '6 * 2', 'is_correct' => true],
                        ['option_text' => '5 * 2', 'is_correct' => false],
                        ['option_text' => 'Addition always first', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print((2 + 3) * 4)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'precedence', 'brackets'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '14', 'is_correct' => false],
                        ['option_text' => '20', 'is_correct' => true],
                        ['option_text' => '24', 'is_correct' => false],
                        ['option_text' => '9', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following expression?',
                    'question_code' => 'print(8 // 2 ** 2)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence', 'division'],
                    'applicable_to' => ['class_10', 'all'],
                    'options' => [
                        ['option_text' => '1', 'is_correct' => false],
                        ['option_text' => '2', 'is_correct' => true],
                        ['option_text' => '4', 'is_correct' => false],
                        ['option_text' => '8', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which operator is evaluated last in the expression 4 + 6 * 2 ** 2?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence'],
                    'applicable_to' => ['class_10', 'all'],
                    'options' => [
                        ['option_text' => '**', 'is_correct' => false],
                        ['option_text' => '*', 'is_correct' => false],
                        ['option_text' => '+', 'is_correct' => true],
                        ['option_text' => '()', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output?',
                    'question_code' => 'print(5 > 3 + 4)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence', 'comparison'],
                    'applicable_to' => ['class_10', 'all'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'What will be the output of the following code?',
                    'question_code' => 'print(not True or False)',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 2,
                    'question_tags' => ['python', 'operators', 'precedence', 'logical'],
                    'applicable_to' => ['class_10', 'all'],
                    'options' => [
                        ['option_text' => 'True', 'is_correct' => false],
                        ['option_text' => 'False', 'is_correct' => true],
                        ['option_text' => 'Error', 'is_correct' => false],
                        ['option_text' => 'None', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'Which statement about operator precedence is correct?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 19,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'operators', 'precedence', 'concept'],
                    'applicable_to' => ['class_9', 'class_10', 'all'],
                    'options' => [
                        ['option_text' => 'Operators are evaluated left to right always', 'is_correct' => false],
                        ['option_text' => 'Parentheses can change evaluation order', 'is_correct' => true],
                        ['option_text' => 'Addition has higher precedence than multiplication', 'is_correct' => false],
                        ['option_text' => 'All operators have equal precedence', 'is_correct' => false],
                    ],
                ],




            ];

            foreach ($questions as $data) {

                $options = $data['options'];
                unset($data['options']);

                $question = Question::create([
                    ...$data,
                    'inforce' => true,
                ]);

                $question->options()->createMany(
                    collect($options)->map(function ($opt) {
                        return [
                            'option_text' => $opt['option_text'],
                            'option_code' => null,
                            'option_image' => null,
                            'is_correct' => $opt['is_correct'],
                            'inforce' => true,
                        ];
                    })->toArray()
                );
            }

        });
    }
}
