<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Question;

class PythonVariablesSyntaxSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            $questions = [

                // ---------- INDENTATION QUESTIONS ----------

                

        [
            'question_text' => 'What is indentation in Python?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'Spaces at the beginning of a line', 'is_correct' => true],
                ['option_text' => 'Blank lines', 'is_correct' => false],
                ['option_text' => 'Comments', 'is_correct' => false],
                ['option_text' => 'Variables', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Why is indentation important in Python?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'It defines code blocks', 'is_correct' => true],
                ['option_text' => 'It increases speed', 'is_correct' => false],
                ['option_text' => 'It stores data', 'is_correct' => false],
                ['option_text' => 'It is optional', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Which error occurs due to incorrect indentation?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'IndentationError', 'is_correct' => true],
                ['option_text' => 'TypeError', 'is_correct' => false],
                ['option_text' => 'NameError', 'is_correct' => false],
                ['option_text' => 'ValueError', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'How many spaces are recommended for indentation in Python?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation', 'pep8'],
            'options' => [
                ['option_text' => '4 spaces', 'is_correct' => true],
                ['option_text' => '2 spaces', 'is_correct' => false],
                ['option_text' => '6 spaces', 'is_correct' => false],
                ['option_text' => '8 spaces', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Which symbol starts an indented block in Python?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => ':', 'is_correct' => true],
                ['option_text' => '{', 'is_correct' => false],
                ['option_text' => ';', 'is_correct' => false],
                ['option_text' => '()', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Is indentation mandatory in Python?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'Yes', 'is_correct' => true],
                ['option_text' => 'No', 'is_correct' => false],
                ['option_text' => 'Only for loops', 'is_correct' => false],
                ['option_text' => 'Only for functions', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Which error occurs when tabs and spaces are mixed?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'TabError', 'is_correct' => true],
                ['option_text' => 'IndexError', 'is_correct' => false],
                ['option_text' => 'ValueError', 'is_correct' => false],
                ['option_text' => 'NameError', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Which statements require indentation?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'if, for, while, def', 'is_correct' => true],
                ['option_text' => 'print only', 'is_correct' => false],
                ['option_text' => 'import only', 'is_correct' => false],
                ['option_text' => 'comments only', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Does Python use curly braces {} for code blocks?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'No', 'is_correct' => true],
                ['option_text' => 'Yes', 'is_correct' => false],
                ['option_text' => 'Sometimes', 'is_correct' => false],
                ['option_text' => 'Only in classes', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Which indentation style improves readability?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'Consistent indentation', 'is_correct' => true],
                ['option_text' => 'Random spaces', 'is_correct' => false],
                ['option_text' => 'No spaces', 'is_correct' => false],
                ['option_text' => 'Mixed tabs and spaces', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Is indentation required inside functions?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'Yes', 'is_correct' => true],
                ['option_text' => 'No', 'is_correct' => false],
                ['option_text' => 'Optional', 'is_correct' => false],
                ['option_text' => 'Only once', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Is indentation required inside loops?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'Yes', 'is_correct' => true],
                ['option_text' => 'No', 'is_correct' => false],
                ['option_text' => 'Only for for-loop', 'is_correct' => false],
                ['option_text' => 'Only for while-loop', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'What happens if indentation levels are inconsistent?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'An error is raised', 'is_correct' => true],
                ['option_text' => 'Code runs normally', 'is_correct' => false],
                ['option_text' => 'Python ignores it', 'is_correct' => false],
                ['option_text' => 'Output changes only', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Which indentation is correct?',
            'question_code' => "if x > 5:\n    print(x)",
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => '4 spaces before print()', 'is_correct' => true],
                ['option_text' => 'No indentation', 'is_correct' => false],
                ['option_text' => 'Random spaces', 'is_correct' => false],
                ['option_text' => 'Using {}', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Indentation in Python replaces which feature of other languages?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'Braces {}', 'is_correct' => true],
                ['option_text' => 'Semicolons', 'is_correct' => false],
                ['option_text' => 'Variables', 'is_correct' => false],
                ['option_text' => 'Functions', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Which block does NOT require indentation?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'print()', 'is_correct' => true],
                ['option_text' => 'if', 'is_correct' => false],
                ['option_text' => 'for', 'is_correct' => false],
                ['option_text' => 'while', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Indentation is checked by Python at which time?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'At runtime', 'is_correct' => true],
                ['option_text' => 'After execution', 'is_correct' => false],
                ['option_text' => 'Never', 'is_correct' => false],
                ['option_text' => 'Only in IDE', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'What does correct indentation mainly improve?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'Readability', 'is_correct' => true],
                ['option_text' => 'Execution speed', 'is_correct' => false],
                ['option_text' => 'Memory usage', 'is_correct' => false],
                ['option_text' => 'Compilation time', 'is_correct' => false],
            ],
        ],

        [
            'question_text' => 'Which indentation practice is recommended?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation'],
            'options' => [
                ['option_text' => 'Use spaces consistently', 'is_correct' => true],
                ['option_text' => 'Mix tabs and spaces', 'is_correct' => false],
                ['option_text' => 'Avoid indentation', 'is_correct' => false],
                ['option_text' => 'Indent randomly', 'is_correct' => false],
            ],
        ],
        [
            'question_text' => 'What will happen if a block of code is not properly indented in Python?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 8,
            'question_level_id' => 1,
            'question_tags' => ['python', 'indentation', 'error'],
            'options' => [
                ['option_text' => 'Python raises an IndentationError', 'is_correct' => true],
                ['option_text' => 'The program runs normally', 'is_correct' => false],
                ['option_text' => 'Only a warning is shown', 'is_correct' => false],
                ['option_text' => 'Python ignores indentation', 'is_correct' => false],
            ],
        ],
       
    //comments questions
    [
        'question_text' => 'What are comments in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Text ignored by the Python interpreter', 'is_correct' => true],
            ['option_text' => 'Executable Python code', 'is_correct' => false],
            ['option_text' => 'Input statements', 'is_correct' => false],
            ['option_text' => 'Error messages', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which symbol is used to write a single-line comment in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => '#', 'is_correct' => true],
            ['option_text' => '//', 'is_correct' => false],
            ['option_text' => '/* */', 'is_correct' => false],
            ['option_text' => '--', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'What is the main purpose of comments?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'To explain and document code', 'is_correct' => true],
            ['option_text' => 'To increase execution speed', 'is_correct' => false],
            ['option_text' => 'To declare variables', 'is_correct' => false],
            ['option_text' => 'To fix runtime errors', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'How does Python treat comments during program execution?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'They are ignored', 'is_correct' => true],
            ['option_text' => 'They are executed', 'is_correct' => false],
            ['option_text' => 'They cause an error', 'is_correct' => false],
            ['option_text' => 'They are printed', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Can comments be written at the end of a line of code?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Yes, using #', 'is_correct' => true],
            ['option_text' => 'No, only on separate lines', 'is_correct' => false],
            ['option_text' => 'Only inside loops', 'is_correct' => false],
            ['option_text' => 'Only inside functions', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which of the following is a correct comment?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => '# This is a comment', 'is_correct' => true],
            ['option_text' => '// This is a comment', 'is_correct' => false],
            ['option_text' => '/* This is a comment */', 'is_correct' => false],
            ['option_text' => '<!-- comment -->', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which style is commonly used for multi-line comments in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Triple-quoted strings', 'is_correct' => true],
            ['option_text' => 'Double slashes', 'is_correct' => false],
            ['option_text' => 'Angle brackets', 'is_correct' => false],
            ['option_text' => 'Semicolons', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'What are docstrings in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Documentation strings for modules, classes, or functions', 'is_correct' => true],
            ['option_text' => 'Error messages', 'is_correct' => false],
            ['option_text' => 'Variable names', 'is_correct' => false],
            ['option_text' => 'Loop statements', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which of the following is NOT a comment in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'print("Hello")', 'is_correct' => true],
            ['option_text' => '# Hello', 'is_correct' => false],
            ['option_text' => '"""Hello"""', 'is_correct' => false],
            ['option_text' => '#print Hello', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Do comments affect the output of a Python program?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'No', 'is_correct' => true],
            ['option_text' => 'Yes', 'is_correct' => false],
            ['option_text' => 'Only multiline comments', 'is_correct' => false],
            ['option_text' => 'Only inline comments', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Can comments be used to disable code temporarily?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Yes', 'is_correct' => true],
            ['option_text' => 'No', 'is_correct' => false],
            ['option_text' => 'Only in loops', 'is_correct' => false],
            ['option_text' => 'Only in classes', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which comment improves code readability?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Descriptive comments', 'is_correct' => true],
            ['option_text' => 'Random comments', 'is_correct' => false],
            ['option_text' => 'Long comments only', 'is_correct' => false],
            ['option_text' => 'Inline code', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which symbol can start a comment anywhere in a line?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => '#', 'is_correct' => true],
            ['option_text' => '//', 'is_correct' => false],
            ['option_text' => '/*', 'is_correct' => false],
            ['option_text' => '<!--', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Are comments mandatory in Python programs?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'No', 'is_correct' => true],
            ['option_text' => 'Yes', 'is_correct' => false],
            ['option_text' => 'Only for large programs', 'is_correct' => false],
            ['option_text' => 'Only for functions', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which comment style is recommended for explaining functions?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Docstrings', 'is_correct' => true],
            ['option_text' => 'Inline comments', 'is_correct' => false],
            ['option_text' => 'Print statements', 'is_correct' => false],
            ['option_text' => 'Variables', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Can comments span multiple lines using #?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Yes, by using # on each line', 'is_correct' => true],
            ['option_text' => 'No, it is not possible', 'is_correct' => false],
            ['option_text' => 'Only in loops', 'is_correct' => false],
            ['option_text' => 'Only in classes', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which of the following best describes an inline comment?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'A comment written after a statement', 'is_correct' => true],
            ['option_text' => 'A comment on multiple lines', 'is_correct' => false],
            ['option_text' => 'A comment inside a loop only', 'is_correct' => false],
            ['option_text' => 'A comment inside a function only', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which practice is recommended while writing comments?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Keep comments clear and relevant', 'is_correct' => true],
            ['option_text' => 'Comment every line', 'is_correct' => false],
            ['option_text' => 'Avoid comments completely', 'is_correct' => false],
            ['option_text' => 'Use comments instead of code', 'is_correct' => false],
        ],
    ],

    [
        'question_text' => 'Which comment helps other programmers understand the code?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 9,
        'question_level_id' => 1,
        'question_tags' => ['python', 'comments'],
        'options' => [
            ['option_text' => 'Descriptive comments', 'is_correct' => true],
            ['option_text' => 'Short comments only', 'is_correct' => false],
            ['option_text' => 'Random comments', 'is_correct' => false],
            ['option_text' => 'Inline code', 'is_correct' => false],
        ],
    ],
    [
    'question_text' => 'Which of the following variable names is NOT valid in Python?',
    'question_code' => null,
    'question_image' => null,
    'question_type_id' => 1,
    'topic_id' => 9,
    'question_level_id' => 1,
    'question_tags' => ['python', 'variables', 'naming'],
    'options' => [
        ['option_text' => 'user_name', 'is_correct' => false],
        ['option_text' => '_userName', 'is_correct' => false],
        ['option_text' => 'userName', 'is_correct' => false],
        ['option_text' => 'user-name', 'is_correct' => true],
    ],
],

//variable and naming convention
  [
        'question_text' => 'Which of the following is allowed as a variable name?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'rules'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => '_value', 'is_correct' => true],
            ['option_text' => 'value$', 'is_correct' => false],
            ['option_text' => 'value@', 'is_correct' => false],
            ['option_text' => 'value%', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which variable name is best practice?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'best_practice'],
        'applicable_to' => ['class_9', 'class_10'],
        'options' => [
            ['option_text' => 'total_marks', 'is_correct' => true],
            ['option_text' => 'tm', 'is_correct' => false],
            ['option_text' => 'x1', 'is_correct' => false],
            ['option_text' => 'T', 'is_correct' => false],
        ],
    ],
      [
        'question_text' => 'Which is the correct way to assign multiple variables?',
        'question_code' => 'a, b = 1, 2',
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'multiple_assignment'],
        'applicable_to' => ['class_9', 'class_10'],
        'options' => [
            ['option_text' => 'a, b = 1, 2', 'is_correct' => true],
            ['option_text' => 'a = 1, b = 2', 'is_correct' => false],
            ['option_text' => '(a,b) = 1,2', 'is_correct' => false],
            ['option_text' => 'a & b = 1,2', 'is_correct' => false],
        ],
    ],
     
    
    [
        'question_text' => 'What happens if you assign a new value to an existing variable?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'update'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => 'The old value is replaced', 'is_correct' => true],
            ['option_text' => 'An error occurs', 'is_correct' => false],
            ['option_text' => 'Both values are stored', 'is_correct' => false],
            ['option_text' => 'Program stops', 'is_correct' => false],
        ],
    ],
     [
        'question_text' => 'Why should variable names be meaningful?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'best_practice'],
        'applicable_to' => ['class_9', 'class_10'],
        'options' => [
            ['option_text' => 'Improves code readability', 'is_correct' => true],
            ['option_text' => 'Increases speed', 'is_correct' => false],
            ['option_text' => 'Avoids syntax errors', 'is_correct' => false],
            ['option_text' => 'Changes output', 'is_correct' => false],
        ],
    ],
   
   
        [
        'question_text' => 'Which symbol is used to assign a value to a variable in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'assignment'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => '=', 'is_correct' => true],
            ['option_text' => '==', 'is_correct' => false],
            ['option_text' => '=>', 'is_correct' => false],
            ['option_text' => ':=', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which of the following is a valid variable name?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'naming'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => 'student_name', 'is_correct' => true],
            ['option_text' => '2student', 'is_correct' => false],
            ['option_text' => 'student-name', 'is_correct' => false],
            ['option_text' => 'student name', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which character is NOT allowed in a Python variable name?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'rules'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => '_ (underscore)', 'is_correct' => false],
            ['option_text' => 'Alphabet', 'is_correct' => false],
            ['option_text' => 'Number (after letter)', 'is_correct' => false],
            ['option_text' => '- (hyphen)', 'is_correct' => true],
        ],
    ],
    [
        'question_text' => 'Can a Python variable start with a number?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'rules'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => 'Yes', 'is_correct' => false],
            ['option_text' => 'No', 'is_correct' => true],
            ['option_text' => 'Only with underscore', 'is_correct' => false],
            ['option_text' => 'Only in Python 3', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which of the following is a correct variable assignment?',
        'question_code' => 'x = 10',
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'assignment'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => 'x = 10', 'is_correct' => true],
            ['option_text' => '10 = x', 'is_correct' => false],
            ['option_text' => 'x == 10', 'is_correct' => false],
            ['option_text' => 'int x = 10', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which naming convention is recommended for Python variables?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'naming_convention'],
        'applicable_to' => ['class_9', 'class_10'],
        'options' => [
            ['option_text' => 'snake_case', 'is_correct' => true],
            ['option_text' => 'camelCase', 'is_correct' => false],
            ['option_text' => 'PascalCase', 'is_correct' => false],
            ['option_text' => 'UPPER-CASE', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which variable name follows snake_case?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'snake_case'],
        'applicable_to' => ['class_9', 'class_10'],
        'options' => [
            ['option_text' => 'total_marks', 'is_correct' => true],
            ['option_text' => 'TotalMarks', 'is_correct' => false],
            ['option_text' => 'totalMarks', 'is_correct' => false],
            ['option_text' => 'total-marks', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Are Python variable names case-sensitive?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'case_sensitive'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => 'Yes', 'is_correct' => true],
            ['option_text' => 'No', 'is_correct' => false],
            ['option_text' => 'Only for strings', 'is_correct' => false],
            ['option_text' => 'Only for numbers', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which of these variables is different from the others?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'case'],
        'applicable_to' => ['class_9', 'class_10'],
        'options' => [
            ['option_text' => 'Age', 'is_correct' => true],
            ['option_text' => 'age', 'is_correct' => false],
            ['option_text' => 'age', 'is_correct' => false],
            ['option_text' => 'age', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which of the following is NOT a valid variable name?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'invalid'],
        'applicable_to' => ['class_8', 'class_9', 'class_10'],
        'options' => [
            ['option_text' => 'total_1', 'is_correct' => false],
            ['option_text' => '_count', 'is_correct' => false],
            ['option_text' => 'class', 'is_correct' => true],
            ['option_text' => 'count', 'is_correct' => false],
        ],
    ],
    
    [
        'question_text' => 'Which keyword cannot be used as a variable name?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 10,
        'question_level_id' => 1,
        'question_tags' => ['python', 'variable', 'keyword'],
        'applicable_to' => ['class_9', 'class_10'],
        'options' => [
            ['option_text' => 'if', 'is_correct' => true],
            ['option_text' => 'score', 'is_correct' => false],
            ['option_text' => 'marks', 'is_correct' => false],
            ['option_text' => 'total', 'is_correct' => false],
        ],
    ],
    //keywords and identifiers
    [
        'question_text' => 'Which keyword is used to define an anonymous function in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords', 'lambda'],
        'options' => [
            ['option_text' => 'lambda', 'is_correct' => true],
            ['option_text' => 'def', 'is_correct' => false],
            ['option_text' => 'anon', 'is_correct' => false],
            ['option_text' => 'func', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which of the following identifiers is NOT valid in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'identifiers', 'rules'],
        'options' => [
            ['option_text' => '_count', 'is_correct' => false],
            ['option_text' => 'count1', 'is_correct' => false],
            ['option_text' => '1count', 'is_correct' => true],
            ['option_text' => 'count_', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which keyword is used when no action is required in a block?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'pass', 'is_correct' => true],
            ['option_text' => 'skip', 'is_correct' => false],
            ['option_text' => 'continue', 'is_correct' => false],
            ['option_text' => 'break', 'is_correct' => false],
        ],
    ],
    [
            'question_text' => 'Which of the following is a valid identifier used for a constant by convention?',
            'question_code' => null,
            'question_image' => null,
            'question_type_id' => 1,
            'topic_id' => 11,
            'question_level_id' => 1,
            'question_tags' => ['python', 'identifiers', 'convention'],
            'options' => [
                ['option_text' => 'MAX_VALUE', 'is_correct' => true],
                ['option_text' => 'max-value', 'is_correct' => false],
                ['option_text' => 'MaxValue()', 'is_correct' => false],
                ['option_text' => 'max value', 'is_correct' => false],
            ],
    ],
    
    [
        'question_text' => 'What are keywords in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'Reserved words with special meaning', 'is_correct' => true],
            ['option_text' => 'User-defined names', 'is_correct' => false],
            ['option_text' => 'Comments in code', 'is_correct' => false],
            ['option_text' => 'Variable values', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Can keywords be used as variable names?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'No', 'is_correct' => true],
            ['option_text' => 'Yes', 'is_correct' => false],
            ['option_text' => 'Only sometimes', 'is_correct' => false],
            ['option_text' => 'Only in functions', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which of the following is a Python keyword?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'if', 'is_correct' => true],
            ['option_text' => 'print', 'is_correct' => false],
            ['option_text' => 'input', 'is_correct' => false],
            ['option_text' => 'value', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which keyword is used to define a function?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'def', 'is_correct' => true],
            ['option_text' => 'function', 'is_correct' => false],
            ['option_text' => 'define', 'is_correct' => false],
            ['option_text' => 'fun', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which keyword is used to check a condition?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'if', 'is_correct' => true],
            ['option_text' => 'for', 'is_correct' => false],
            ['option_text' => 'print', 'is_correct' => false],
            ['option_text' => 'return', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'What are identifiers in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'identifiers'],
        'options' => [
            ['option_text' => 'Names used to identify variables, functions, etc.', 'is_correct' => true],
            ['option_text' => 'Reserved words', 'is_correct' => false],
            ['option_text' => 'Comments', 'is_correct' => false],
            ['option_text' => 'Operators', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which of the following is a valid identifier?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'identifiers'],
        'options' => [
            ['option_text' => 'total_marks', 'is_correct' => true],
            ['option_text' => '2marks', 'is_correct' => false],
            ['option_text' => 'total-marks', 'is_correct' => false],
            ['option_text' => 'total marks', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which character is allowed in identifiers?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'identifiers'],
        'options' => [
            ['option_text' => 'Underscore (_)', 'is_correct' => true],
            ['option_text' => 'Hyphen (-)', 'is_correct' => false],
            ['option_text' => 'Space', 'is_correct' => false],
            ['option_text' => '@', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Can an identifier start with a number?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'identifiers'],
        'options' => [
            ['option_text' => 'No', 'is_correct' => true],
            ['option_text' => 'Yes', 'is_correct' => false],
            ['option_text' => 'Only in Python 3', 'is_correct' => false],
            ['option_text' => 'Only with underscore', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Are Python identifiers case-sensitive?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'identifiers'],
        'options' => [
            ['option_text' => 'Yes', 'is_correct' => true],
            ['option_text' => 'No', 'is_correct' => false],
            ['option_text' => 'Only for functions', 'is_correct' => false],
            ['option_text' => 'Only for variables', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which of the following is NOT a Python keyword?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'while', 'is_correct' => false],
            ['option_text' => 'return', 'is_correct' => false],
            ['option_text' => 'for', 'is_correct' => false],
            ['option_text' => 'display', 'is_correct' => true],
        ],
    ],
    [
        'question_text' => 'Which keyword is used to exit a loop?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'break', 'is_correct' => true],
            ['option_text' => 'stop', 'is_correct' => false],
            ['option_text' => 'exit', 'is_correct' => false],
            ['option_text' => 'end', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which keyword is used to skip the current iteration?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'continue', 'is_correct' => true],
            ['option_text' => 'skip', 'is_correct' => false],
            ['option_text' => 'pass', 'is_correct' => false],
            ['option_text' => 'next', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which keyword is used to define a class?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'class', 'is_correct' => true],
            ['option_text' => 'struct', 'is_correct' => false],
            ['option_text' => 'object', 'is_correct' => false],
            ['option_text' => 'define', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which keyword is used to return a value from a function?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'return', 'is_correct' => true],
            ['option_text' => 'output', 'is_correct' => false],
            ['option_text' => 'print', 'is_correct' => false],
            ['option_text' => 'send', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which keyword is used to handle exceptions?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'try', 'is_correct' => true],
            ['option_text' => 'catch', 'is_correct' => false],
            ['option_text' => 'error', 'is_correct' => false],
            ['option_text' => 'handle', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which keyword is used to define a loop that runs a fixed number of times?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'keywords'],
        'options' => [
            ['option_text' => 'for', 'is_correct' => true],
            ['option_text' => 'while', 'is_correct' => false],
            ['option_text' => 'loop', 'is_correct' => false],
            ['option_text' => 'repeat', 'is_correct' => false],
        ],
    ],
    [
        'question_text' => 'Which identifier naming style is recommended in Python?',
        'question_code' => null,
        'question_image' => null,
        'question_type_id' => 1,
        'topic_id' => 11,
        'question_level_id' => 1,
        'question_tags' => ['python', 'identifiers', 'naming'],
        'options' => [
            ['option_text' => 'snake_case', 'is_correct' => true],
            ['option_text' => 'camelCase', 'is_correct' => false],
            ['option_text' => 'PascalCase', 'is_correct' => false],
            ['option_text' => 'kebab-case', 'is_correct' => false],
        ],
    ],
];
            
 foreach ($questions as $data) {

                $options = $data['options'];
                unset($data['options']);

                $question = Question::create([
                    ...$data,
                    'inforce' => true,
                ]);

                $question->options()->createMany(
                    collect($options)->map(function ($opt) {
                        return [
                            'option_text' => $opt['option_text'],
                            'option_code' => null,
                            'option_image' => null,
                            'is_correct' => $opt['is_correct'],
                            'inforce' => true,
                        ];
                    })->toArray()
                );
            }

        });
    }
}
