<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Question;

class PythonListIntroductionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::transaction(function () {

            $questions = [
                [
                    'question_text' => 'What is a list in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'basics'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10', 'all'],
                    'options' => [
                        ['option_text' => 'A collection of ordered and mutable elements', 'is_correct' => true],
                        ['option_text' => 'A fixed-size array', 'is_correct' => false],
                        ['option_text' => 'A key-value data structure', 'is_correct' => false],
                        ['option_text' => 'A function in Python', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which brackets are used to define a list in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'syntax'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '()', 'is_correct' => false],
                        ['option_text' => '{}', 'is_correct' => false],
                        ['option_text' => '[]', 'is_correct' => true],
                        ['option_text' => '<>', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which of the following is a valid Python list?',
                    'question_code' => 'A = [1, "apple", 3.5]',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'examples'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'A = (1, 2, 3)', 'is_correct' => false],
                        ['option_text' => 'A = {1, 2, 3}', 'is_correct' => false],
                        ['option_text' => 'A = [1, "apple", 3.5]', 'is_correct' => true],
                        ['option_text' => 'A = <1, 2, 3>', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which index is used to access the first element of a Python list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'indexing'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '0', 'is_correct' => true],
                        ['option_text' => '1', 'is_correct' => false],
                        ['option_text' => '-1', 'is_correct' => false],
                        ['option_text' => 'First', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Are Python lists mutable?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'mutable'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Yes, elements can be changed', 'is_correct' => true],
                        ['option_text' => 'No, they are immutable', 'is_correct' => false],
                        ['option_text' => 'Only numbers can be changed', 'is_correct' => false],
                        ['option_text' => 'Only strings can be changed', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which function is used to find the number of elements in a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'length'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'size()', 'is_correct' => false],
                        ['option_text' => 'length()', 'is_correct' => false],
                        ['option_text' => 'len()', 'is_correct' => true],
                        ['option_text' => 'count()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method is used to add an element at the end of a Python list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'append'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'add()', 'is_correct' => false],
                        ['option_text' => 'append()', 'is_correct' => true],
                        ['option_text' => 'insert()', 'is_correct' => false],
                        ['option_text' => 'extend()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method is used to remove the last element from a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'pop'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'delete()', 'is_correct' => false],
                        ['option_text' => 'remove()', 'is_correct' => false],
                        ['option_text' => 'pop()', 'is_correct' => true],
                        ['option_text' => 'clear()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output of the following code?',
                    'question_code' => 'A = [10, 20, 30]\nprint(A[1])',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'index'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '10', 'is_correct' => false],
                        ['option_text' => '20', 'is_correct' => true],
                        ['option_text' => '30', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method removes a specific element from a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'remove'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'pop()', 'is_correct' => false],
                        ['option_text' => 'delete()', 'is_correct' => false],
                        ['option_text' => 'remove()', 'is_correct' => true],
                        ['option_text' => 'clear()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method is used to add elements of another list to the current list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'extend'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'append()', 'is_correct' => false],
                        ['option_text' => 'add()', 'is_correct' => false],
                        ['option_text' => 'extend()', 'is_correct' => true],
                        ['option_text' => 'insert()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What does the clear() method do?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'clear'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Deletes the list', 'is_correct' => false],
                        ['option_text' => 'Removes all elements from the list', 'is_correct' => true],
                        ['option_text' => 'Removes last element', 'is_correct' => false],
                        ['option_text' => 'Sorts the list', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which operator is used to repeat a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'operators'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '+', 'is_correct' => false],
                        ['option_text' => '*', 'is_correct' => true],
                        ['option_text' => '/', 'is_correct' => false],
                        ['option_text' => '%', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which of the following creates an empty list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'creation'],
                    'applicable_to' => ['class_8', 'class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'list()', 'is_correct' => true],
                        ['option_text' => '()', 'is_correct' => false],
                        ['option_text' => '{}', 'is_correct' => false],
                        ['option_text' => '<>', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which function is used to find the maximum value in a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'max'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'maximum()', 'is_correct' => false],
                        ['option_text' => 'max()', 'is_correct' => true],
                        ['option_text' => 'top()', 'is_correct' => false],
                        ['option_text' => 'largest()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method is used to sort a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 39,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'sort'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'order()', 'is_correct' => false],
                        ['option_text' => 'sort()', 'is_correct' => true],
                        ['option_text' => 'arrange()', 'is_correct' => false],
                        ['option_text' => 'sequence()', 'is_correct' => false],
                    ],
                ],

                [
                    'question_text' => 'How do you access the first element of a list named my_list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'indexing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'my_list[0]', 'is_correct' => true],
                        ['option_text' => 'my_list[1]', 'is_correct' => false],
                        ['option_text' => 'my_list[-1]', 'is_correct' => false],
                        ['option_text' => 'my_list(first)', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which index number is used to access the last element of a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'indexing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '0', 'is_correct' => false],
                        ['option_text' => '1', 'is_correct' => false],
                        ['option_text' => '-1', 'is_correct' => true],
                        ['option_text' => 'last', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What does my_list[2:5] return?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'slicing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Elements from index 2 to 5 including 5', 'is_correct' => false],
                        ['option_text' => 'Elements from index 2 to 4', 'is_correct' => true],
                        ['option_text' => 'Elements from index 0 to 5', 'is_correct' => false],
                        ['option_text' => 'Only the element at index 5', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which slicing returns all elements of a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'slicing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'my_list[:]', 'is_correct' => true],
                        ['option_text' => 'my_list[0]', 'is_correct' => false],
                        ['option_text' => 'my_list[-1:]', 'is_correct' => false],
                        ['option_text' => 'my_list(all)', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What does my_list[:3] return?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'slicing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'First three elements', 'is_correct' => true],
                        ['option_text' => 'Last three elements', 'is_correct' => false],
                        ['option_text' => 'Elements from index 3 onward', 'is_correct' => false],
                        ['option_text' => 'Only element at index 3', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which index is invalid for a list of length 5?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'indexing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '0', 'is_correct' => false],
                        ['option_text' => '4', 'is_correct' => false],
                        ['option_text' => '5', 'is_correct' => true],
                        ['option_text' => '-1', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What does my_list[-2] return?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'negative indexing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Second element', 'is_correct' => false],
                        ['option_text' => 'Second last element', 'is_correct' => true],
                        ['option_text' => 'Last element', 'is_correct' => false],
                        ['option_text' => 'First element', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which slicing extracts elements from index 1 to the end?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'slicing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'my_list[1:]', 'is_correct' => true],
                        ['option_text' => 'my_list[:1]', 'is_correct' => false],
                        ['option_text' => 'my_list[-1:]', 'is_correct' => false],
                        ['option_text' => 'my_list[1]', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What does my_list[::2] do?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'slicing', 'step'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Returns every second element', 'is_correct' => true],
                        ['option_text' => 'Returns last two elements', 'is_correct' => false],
                        ['option_text' => 'Returns first two elements', 'is_correct' => false],
                        ['option_text' => 'Reverses the list', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which slicing reverses a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 40,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'slicing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'my_list[::-1]', 'is_correct' => true],
                        ['option_text' => 'my_list[-1]', 'is_correct' => false],
                        ['option_text' => 'my_list[1:]', 'is_correct' => false],
                        ['option_text' => 'reverse(my_list)', 'is_correct' => false],
                    ],

                ],



                [
                    'question_text' => 'Which method is used to add an element at the end of a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'append'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'add()', 'is_correct' => false],
                        ['option_text' => 'append()', 'is_correct' => true],
                        ['option_text' => 'insert()', 'is_correct' => false],
                        ['option_text' => 'extend()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method removes a specific element from a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'remove'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'delete()', 'is_correct' => false],
                        ['option_text' => 'remove()', 'is_correct' => true],
                        ['option_text' => 'pop()', 'is_correct' => false],
                        ['option_text' => 'clear()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method removes and returns the last element of a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'pop'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'remove()', 'is_correct' => false],
                        ['option_text' => 'pop()', 'is_correct' => true],
                        ['option_text' => 'delete()', 'is_correct' => false],
                        ['option_text' => 'clear()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method removes all elements from a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'clear'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'remove()', 'is_correct' => false],
                        ['option_text' => 'delete()', 'is_correct' => false],
                        ['option_text' => 'clear()', 'is_correct' => true],
                        ['option_text' => 'pop()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method is used to add multiple elements to a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'extend'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'append()', 'is_correct' => false],
                        ['option_text' => 'insert()', 'is_correct' => false],
                        ['option_text' => 'extend()', 'is_correct' => true],
                        ['option_text' => 'add()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method is used to insert an element at a specific position?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'insert'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'append()', 'is_correct' => false],
                        ['option_text' => 'add()', 'is_correct' => false],
                        ['option_text' => 'insert()', 'is_correct' => true],
                        ['option_text' => 'extend()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method returns the number of elements in a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'count'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'length()', 'is_correct' => false],
                        ['option_text' => 'size()', 'is_correct' => false],
                        ['option_text' => 'count()', 'is_correct' => true],
                        ['option_text' => 'total()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method returns the index of the first occurrence of an element?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'index'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'find()', 'is_correct' => false],
                        ['option_text' => 'search()', 'is_correct' => false],
                        ['option_text' => 'index()', 'is_correct' => true],
                        ['option_text' => 'locate()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method is used to sort a list permanently?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'sort'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'order()', 'is_correct' => false],
                        ['option_text' => 'sorted()', 'is_correct' => false],
                        ['option_text' => 'sort()', 'is_correct' => true],
                        ['option_text' => 'arrange()', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which method reverses the elements of a list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 41,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'reverse'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'invert()', 'is_correct' => false],
                        ['option_text' => 'reverse()', 'is_correct' => true],
                        ['option_text' => 'backward()', 'is_correct' => false],
                        ['option_text' => 'sort()', 'is_correct' => false],
                    ],
                ],


                [
                    'question_text' => 'What is the main purpose of list comprehension in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'To write loops in multiple lines', 'is_correct' => false],
                        ['option_text' => 'To create lists in a single line', 'is_correct' => true],
                        ['option_text' => 'To delete list elements', 'is_correct' => false],
                        ['option_text' => 'To sort lists', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which of the following is the correct syntax of list comprehension?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'syntax'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '[expression for item in list]', 'is_correct' => true],
                        ['option_text' => '(expression for item in list)', 'is_correct' => false],
                        ['option_text' => '{expression for item in list}', 'is_correct' => false],
                        ['option_text' => '[for item in list expression]', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output of: [x for x in range(5)]?',
                    'question_code' => '[x for x in range(5)]',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension', 'output'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '[1, 2, 3, 4, 5]', 'is_correct' => false],
                        ['option_text' => '[0, 1, 2, 3, 4]', 'is_correct' => true],
                        ['option_text' => '[0, 1, 2, 3, 4, 5]', 'is_correct' => false],
                        ['option_text' => '[5]', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which list comprehension creates a list of even numbers from 1 to 10?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension', 'condition'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '[x for x in range(1,11) if x % 2 == 0]', 'is_correct' => true],
                        ['option_text' => '[x if x % 2 == 0 for x in range(1,11)]', 'is_correct' => false],
                        ['option_text' => '[x for x in range(1,10) if x % 2]', 'is_correct' => false],
                        ['option_text' => '[x in range(1,11) if x % 2 == 0]', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What does the condition part in list comprehension do?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension', 'filter'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Sorts the list', 'is_correct' => false],
                        ['option_text' => 'Filters elements', 'is_correct' => true],
                        ['option_text' => 'Deletes elements', 'is_correct' => false],
                        ['option_text' => 'Reverses the list', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which list comprehension creates squares of numbers from 1 to 5?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension', 'math'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '[x*x for x in range(1,6)]', 'is_correct' => true],
                        ['option_text' => '[x^2 for x in range(1,6)]', 'is_correct' => false],
                        ['option_text' => '[x**2 for x in range(1,5)]', 'is_correct' => false],
                        ['option_text' => '[square(x) for x in range(1,6)]', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which bracket is used in list comprehension?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '()', 'is_correct' => false],
                        ['option_text' => '{}', 'is_correct' => false],
                        ['option_text' => '[]', 'is_correct' => true],
                        ['option_text' => '<>', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output of: [x+1 for x in [1,2,3]]?',
                    'question_code' => '[x+1 for x in [1,2,3]]',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension', 'output'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '[1, 2, 3]', 'is_correct' => false],
                        ['option_text' => '[2, 3, 4]', 'is_correct' => true],
                        ['option_text' => '[1, 3, 5]', 'is_correct' => false],
                        ['option_text' => '[2, 4, 6]', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which list comprehension filters values greater than 5?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension', 'condition'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '[x for x in range(10) if x > 5]', 'is_correct' => true],
                        ['option_text' => '[x > 5 for x in range(10)]', 'is_correct' => false],
                        ['option_text' => '[if x > 5 for x in range(10)]', 'is_correct' => false],
                        ['option_text' => '[x for range(10) if x > 5]', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which statement about list comprehension is correct?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 42,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'comprehension'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'It always replaces loops', 'is_correct' => false],
                        ['option_text' => 'It is shorter and more readable', 'is_correct' => true],
                        ['option_text' => 'It works only with numbers', 'is_correct' => false],
                        ['option_text' => 'It cannot use conditions', 'is_correct' => false],
                    ],
                ],


                [
                    'question_text' => 'What is a nested list in Python?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'A list with only numbers', 'is_correct' => false],
                        ['option_text' => 'A list inside another list', 'is_correct' => true],
                        ['option_text' => 'A list without elements', 'is_correct' => false],
                        ['option_text' => 'A sorted list', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'How do you access the first element of the first sublist?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested', 'indexing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'my_list[0][0]', 'is_correct' => true],
                        ['option_text' => 'my_list[1][0]', 'is_correct' => false],
                        ['option_text' => 'my_list[0,0]', 'is_correct' => false],
                        ['option_text' => 'my_list(0)(0)', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What will be the output of: my_list = [[1,2],[3,4]]; print(my_list[1][0])?',
                    'question_code' => 'my_list = [[1,2],[3,4]]\nprint(my_list[1][0])',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested', 'output'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '1', 'is_correct' => false],
                        ['option_text' => '2', 'is_correct' => false],
                        ['option_text' => '3', 'is_correct' => true],
                        ['option_text' => '4', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which of the following is an example of a nested list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '[1, 2, 3]', 'is_correct' => false],
                        ['option_text' => '[[1, 2], [3, 4]]', 'is_correct' => true],
                        ['option_text' => '(1, 2, 3)', 'is_correct' => false],
                        ['option_text' => '{1, 2, 3}', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'How many elements are in the list: [[1,2,3],[4,5,6]]?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '2', 'is_correct' => true],
                        ['option_text' => '3', 'is_correct' => false],
                        ['option_text' => '6', 'is_correct' => false],
                        ['option_text' => '1', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which loop is commonly used to access elements of a nested list?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested', 'loop'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'if loop', 'is_correct' => false],
                        ['option_text' => 'while loop only', 'is_correct' => false],
                        ['option_text' => 'nested for loop', 'is_correct' => true],
                        ['option_text' => 'switch loop', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'What does len([[1,2],[3,4],[5,6]]) return?',
                    'question_code' => 'len([[1,2],[3,4],[5,6]])',
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested', 'len'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => '2', 'is_correct' => false],
                        ['option_text' => '3', 'is_correct' => true],
                        ['option_text' => '6', 'is_correct' => false],
                        ['option_text' => 'Error', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'How do you change the value 4 to 10 in the list my_list = [[1,2],[3,4]]?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested', 'update'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'my_list[1][1] = 10', 'is_correct' => true],
                        ['option_text' => 'my_list[4] = 10', 'is_correct' => false],
                        ['option_text' => 'my_list[1] = 10', 'is_correct' => false],
                        ['option_text' => 'my_list(1)(1) = 10', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which indexing is used to access elements in nested lists?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested', 'indexing'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Single indexing', 'is_correct' => false],
                        ['option_text' => 'Double indexing', 'is_correct' => true],
                        ['option_text' => 'Negative indexing only', 'is_correct' => false],
                        ['option_text' => 'Index slicing', 'is_correct' => false],
                    ],
                ],
                [
                    'question_text' => 'Which operation is NOT possible with nested lists?',
                    'question_code' => null,
                    'question_image' => null,
                    'question_type_id' => 1,
                    'topic_id' => 43,
                    'question_level_id' => 1,
                    'question_tags' => ['python', 'list', 'nested'],
                    'applicable_to' => ['class_9', 'class_10'],
                    'options' => [
                        ['option_text' => 'Accessing elements', 'is_correct' => false],
                        ['option_text' => 'Modifying elements', 'is_correct' => false],
                        ['option_text' => 'Looping through elements', 'is_correct' => false],
                        ['option_text' => 'Executing SQL queries', 'is_correct' => true],
                    ],
                ],








            ];

            foreach ($questions as $data) {

                $options = $data['options'];
                unset($data['options']);

                $question = Question::create([
                    ...$data,
                    'inforce' => true,
                ]);

                $question->options()->createMany(
                    collect($options)->map(function ($opt) {
                        return [
                            'option_text' => $opt['option_text'],
                            'option_code' => null,
                            'option_image' => null,
                            'is_correct' => $opt['is_correct'],
                            'inforce' => true,
                        ];
                    })->toArray()
                );
            }

        });
    }
}
